# Generated by Django 5.0.3 on 2024-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
